/**
 * Inbound control-plane protocol as tagged unions (mirrors Protocol.kt).
 *
 * The rule: raw JSON only exists at the socket boundary. Everything inside the
 * server sees parsed, closed variants — and every consumer switches exhaustively,
 * so adding a variant is a compile error everywhere it matters.
 */

export type ClientCommandKind = "stop" | "repeat" | "cancel_capture";

export interface Hello {
  tag: "hello";
  device: string;
  /** Stable opaque ID generated and persisted by one handset installation. */
  installationId: string;
  token?: string;
}

export interface Command {
  tag: "command";
  kind: ClientCommandKind;
  /** Opaque identifier generated by the handset for this command's turn. */
  turnToken: string;
}

/** Client says: stop capturing, send what you have (tap during capturing). */
export interface UtteranceEnd {
  tag: "utterance_end";
  turnToken: string;
}

/** Double-pinch: next utterance goes to the meta agent, not Hermes. */
export interface MetaMode {
  tag: "meta_mode";
  turnToken: string;
}

/** Phone snapshots the active lane before opening the mic for a turn. */
export interface LaneSelection {
  tag: "lane";
  id: string;
  revision?: number;
  /** Starts a capture turn. This is required; legacy untagged lanes are invalid. */
  turnToken: string;
}

/** Phone confirms that it accepted a synchronous Hermes reply for playback. */
export interface ReplyAck {
  tag: "reply_ack";
  laneId: string;
  replyTo: string;
  afterSeq: number;
  throughSeq: number;
  turnToken: string;
  interactionId: string;
}

/**
 * The handset has durably recorded the complete reply envelope.  This is
 * deliberately earlier than `reply_ack`: it proves a replayable receipt
 * exists locally, but does not authorize telepathosd delivery consumption.
 */
export interface ReplyReceived {
  tag: "reply_received";
  laneId: string;
  replyTo: string;
  afterSeq: number;
  throughSeq: number;
  turnToken: string;
  interactionId: string;
}

/**
 * The handset has durably recorded the bridge's delivery-consumed
 * confirmation and is ready for the bridge to retire its durable binding.
 * This is deliberately distinct from `reply_ack`: the latter authorizes the
 * external delivery consume, while this terminal frame can never do so.
 */
export interface ReplyAckRetire {
  tag: "reply_ack_retire";
  laneId: string;
  replyTo: string;
  afterSeq: number;
  throughSeq: number;
  turnToken: string;
  interactionId: string;
}

export type ControlMsg = Hello | Command | UtteranceEnd | MetaMode | LaneSelection | ReplyReceived | ReplyAck | ReplyAckRetire;

/**
 * Outbound WebSocket frames. `turn_token` is supplied by the handset and
 * `interaction_id` is allocated by the bridge. The three reply-bearing
 * variants deliberately require both values: an old socket frame must never
 * be accepted as a reply for a newer handset turn.
 */
export type ServerMsg =
  | { type: "ready" }
  | { type: "speech_start" }
  | { type: "utterance"; samples: number }
  | {
      type: "stt";
      text: string;
      confidence?: number;
      repo?: string;
      turn_token: string;
      interaction_id: string;
    }
  | { type: "agent_delta"; text: string; turn_token: string; interaction_id: string }
  | {
      type: "agent_end";
      /** Complete reply retained in the durable bridge replay envelope. */
      text: string;
      turn_token: string;
      interaction_id: string;
      lane_id?: string;
      reply_to?: string;
      after_seq?: number;
      through_seq?: number;
    }
  | {
      /** The bridge durably recorded the handset's replayable receipt. */
      type: "reply_received";
      lane_id: string;
      reply_to: string;
      after_seq: number;
      through_seq: number;
      turn_token: string;
      interaction_id: string;
    }
  | {
      type: "reply_acknowledged";
      lane_id: string;
      reply_to: string;
      after_seq: number;
      through_seq: number;
      turn_token: string;
      interaction_id: string;
    }
  | {
      type: "reply_ack_retired";
      lane_id: string;
      reply_to: string;
      after_seq: number;
      through_seq: number;
      turn_token: string;
      interaction_id: string;
    }
  | { type: "listening" }
  | { type: "phase"; value: string }
  | { type: "error"; message: string };

/** Compile-time exhaustiveness guard: if a variant is unhandled, this fails to build. */
export function assertNever(x: never): never {
  throw new Error(`unhandled variant: ${JSON.stringify(x)}`);
}

const COMMAND_KINDS: readonly ClientCommandKind[] = ["stop", "repeat", "cancel_capture"];
/** Maximum UTF-16 code units in a handset turn token; UUIDs are 36 characters. */
export const MAX_TURN_TOKEN_LENGTH = 128;
/** Maximum receipt sequence that survives a JSON number round-trip exactly. */
export const MAX_SAFE_SEQUENCE = Number.MAX_SAFE_INTEGER;
/**
 * Installation IDs are opaque, durable per-installation ownership handles.
 * They are deliberately separate from the human-readable device label.
 */
export const MAX_INSTALLATION_ID_LENGTH = 128;
/** Lane IDs are shared with Rust and Android: ASCII, bounded in both the
 * UTF-8 wire encoding and UTF-16 string length, with no quoting characters. */
export const MAX_LANE_ID_LENGTH = 128;
/** Shared opaque correlation-ID bound: UTF-16 units and UTF-8 bytes. */
export const MAX_OPAQUE_ID_LENGTH = 256;
export const MAX_OPAQUE_ID_BYTES = 256;
const LANE_ID_GRAMMAR = /^[A-Za-z0-9](?:[A-Za-z0-9:_-]*[A-Za-z0-9])?$/;
export const isValidLaneId = (value: unknown): value is string =>
  typeof value === "string" &&
  value.length >= 1 && value.length <= MAX_LANE_ID_LENGTH &&
  Buffer.byteLength(value, "utf8") <= MAX_LANE_ID_LENGTH &&
  LANE_ID_GRAMMAR.test(value);
export const isValidTurnToken = (value: unknown): value is string =>
  typeof value === "string" &&
  value.length >= 1 && value.length <= MAX_TURN_TOKEN_LENGTH &&
  isWellFormedUtf16(value) &&
  !isProtocolBlank(value);
const OPAQUE_ID_CONTROL_CHARACTER = /[\u0000-\u001f\u007f-\u009f]/;
function isWellFormedUtf16(value: string): boolean {
  for (let index = 0; index < value.length; index += 1) {
    const code = value.charCodeAt(index);
    if (code >= 0xd800 && code <= 0xdbff) {
      const next = value.charCodeAt(index + 1);
      if (!(next >= 0xdc00 && next <= 0xdfff)) return false;
      index += 1;
    } else if (code >= 0xdc00 && code <= 0xdfff) {
      return false;
    }
  }
  return true;
}

/**
 * Canonical protocol blankness, independent of a runtime's `trim` behavior:
 * the blank code points are ASCII U+0009..U+000D and U+0020, Unicode
 * White_Space additions U+0085, U+00A0, U+1680, U+2000..U+200A,
 * U+2028..U+2029, U+202F, U+205F, U+3000, plus U+FEFF. A protocol value is
 * blank only when every code point is in that explicit set. This does not
 * trim or normalize the value; callers retain their existing control policy.
 */
function isProtocolBlank(value: string): boolean {
  let sawCodePoint = false;
  for (const character of value) {
    sawCodePoint = true;
    const codePoint = character.codePointAt(0)!;
    if (!(
      (codePoint >= 0x0009 && codePoint <= 0x000d) ||
      codePoint === 0x0020 ||
      codePoint === 0x0085 ||
      codePoint === 0x00a0 ||
      codePoint === 0x1680 ||
      (codePoint >= 0x2000 && codePoint <= 0x200a) ||
      (codePoint >= 0x2028 && codePoint <= 0x2029) ||
      codePoint === 0x202f ||
      codePoint === 0x205f ||
      codePoint === 0x3000 ||
      codePoint === 0xfeff
    )) return false;
  }
  return sawCodePoint;
}

/**
 * Opaque reply/message/interaction IDs are not normalized. They must be
 * nonblank, bounded in both runtime string units, and free of controls.
 */
export const isValidOpaqueId = (value: unknown): value is string =>
  typeof value === "string" &&
  value.length >= 1 && value.length <= MAX_OPAQUE_ID_LENGTH &&
  Buffer.byteLength(value, "utf8") >= 1 && Buffer.byteLength(value, "utf8") <= MAX_OPAQUE_ID_BYTES &&
  !isProtocolBlank(value) && isWellFormedUtf16(value) && !OPAQUE_ID_CONTROL_CHARACTER.test(value);
export const isValidReceiptSequence = (value: unknown): value is number =>
  typeof value === "number" &&
  Number.isSafeInteger(value) && value >= 0 && value <= MAX_SAFE_SEQUENCE;
const CONTROL_CHARACTER = /[\u0000-\u001f\u007f-\u009f]/;

/**
 * Preserve the exact opaque value rather than normalizing it: whitespace or
 * case changes must not silently become a different installation owner.
 */
export function isValidInstallationId(value: unknown): value is string {
  return typeof value === "string" &&
    value.length >= 1 &&
    value.length <= MAX_INSTALLATION_ID_LENGTH &&
    isWellFormedUtf16(value) &&
    !isProtocolBlank(value) &&
    !CONTROL_CHARACTER.test(value);
}

/** Defensive parse: anything malformed or unknown becomes null. Total function. */
export function parseControl(raw: string): ControlMsg | null {
  let msg: any;
  try {
    msg = JSON.parse(raw);
  } catch {
    return null;
  }
  if (typeof msg !== "object" || msg === null) return null;

  switch (msg.type) {
    case "hello":
      return typeof msg.device === "string" && isValidInstallationId(msg.installation_id) &&
        (msg.token === undefined || typeof msg.token === "string")
        ? {
            tag: "hello",
            device: msg.device,
            installationId: msg.installation_id,
            token: msg.token,
          }
        : null;
    case "command":
      return COMMAND_KINDS.includes(msg.command) && isValidTurnToken(msg.turn_token)
        ? { tag: "command", kind: msg.command, turnToken: msg.turn_token }
        : null;
    case "utterance_end":
      return isValidTurnToken(msg.turn_token)
        ? { tag: "utterance_end", turnToken: msg.turn_token }
        : null;
    case "meta_mode":
      return isValidTurnToken(msg.turn_token)
        ? { tag: "meta_mode", turnToken: msg.turn_token }
        : null;
    case "lane":
      return isValidLaneId(msg.id) && isValidTurnToken(msg.turn_token) &&
        (msg.revision === undefined ||
          (Number.isSafeInteger(msg.revision) && msg.revision >= 0))
        ? {
            tag: "lane",
            id: msg.id,
            turnToken: msg.turn_token,
            ...(msg.revision !== undefined && { revision: msg.revision }),
          }
        : null;
    case "reply_received":
    case "reply_ack":
    case "reply_ack_retire":
      return isValidLaneId(msg.lane_id) && isValidOpaqueId(msg.reply_to) &&
        isValidTurnToken(msg.turn_token) && isValidOpaqueId(msg.interaction_id) &&
        isValidReceiptSequence(msg.after_seq) &&
        isValidReceiptSequence(msg.through_seq) && msg.through_seq > msg.after_seq
        ? {
            tag: msg.type,
            laneId: msg.lane_id,
            replyTo: msg.reply_to,
            afterSeq: msg.after_seq,
            throughSeq: msg.through_seq,
            turnToken: msg.turn_token,
            interactionId: msg.interaction_id,
          }
        : null;
    default:
      return null;
  }
}
